version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11
    steps:
      - checkout
      - run:
          name: Test
          command: npm install && npm test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - test